#[colors.bright]
#black = "0x5f5f5f"
#blue = "0x696057"
#cyan = "0x525f66"
#green = "0x6f6749"
#magenta = "0x6f5a59"
#red = "0x785850"
#white = "0xcdcdcd"
#yellow = "0x776049"
#
#[colors.normal]
#black = "0x353535"
#blue = "0x61564b"
#cyan = "0x435861"
#green = "0x6d6137"
#magenta = "0x6b4a49"
#red = "0x744b40"
#white = "0xb3b3b3"
#yellow = "0x765636"
#
#[colors.primary]
#background = "0x181b20"
#foreground = "0x9b9081"


[general]
import = [
  "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml",
]
[font]
size = 11.0 


[font.normal]
family = "FiraMono Nerd Font"
style = "Medium"


[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"


[font.bold_italic]
family = "FiraMono Nerd Font"
style = "Bold Italic"


[font.italic]
family = "FiraMono Nerd Font"
style = "Italic"


[window]
dynamic_padding = true
opacity = 0.85

[window.padding]
x = 4
y = 4
